### ISSUE TITLE
OpenCV returning NULL

### ISSUE THREAD

**Issue by momenso** [mossblaser/HeartMonitor#1]
Any ideas on what may be happening here?

Traceback (most recent call last):
  File "heartMonitor.py", line 530, in <module>
    Program().run()
  File "heartMonitor.py", line 421, in **init**
    self.face_detector = FaceDetector(*self.cam.get_size())
  File "heartMonitor.py", line 53, in **init**
    self.cascade = cv.Load(cascade_file)
TypeError: OpenCV returned NULL

Thank you.

**Comment by tivie** [comment]
you need to include the xml file in the same directory

**Comment by sonineha2191** [comment]
Please help me with
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-9-91a2ffa00be2> in <module>
----> 1 import cv

ModuleNotFoundError: No module named 'cv'

I am using python 3, replacing cv with cv2 is also creating issues in functions like: cv.GetCaptureProperty

**Comment by mossblaser** [comment]
I'm afraid I've long forgotten which version of Open CV I was using when I wrote this; I'm afraid there's a reasonable chance that this code will need some fiddling to get working on newer versions of OpenCV. I'd welcome a PR if you manage to get it working again :).

**Comment by sonineha2191** [comment]
Thanks a ton, will surely look into it
